module.exports = grammar({
  name: 'todo',
  extras: $ => [/\r/],
  rules: {
    document: $ => repeat(choice($.project, $.todo_done, $.todo_cancelled, $.todo_pending, $.comment, $.empty_line)),
    project: $ => seq(optional($._indent), $.project_name, ':', optional(seq(/[ \t]+/, $.tags)), $._eol),
    project_name: $ => /[^\n\r:]+/,
    todo_pending: $ => seq(optional($._indent), $.pending_symbol, /[ \t]+/, $.task_content, $._eol),
    todo_done: $ => seq(optional($._indent), $.done_symbol, /[ \t]+/, $.task_content, $._eol),
    todo_cancelled: $ => seq(optional($._indent), $.cancelled_symbol, /[ \t]+/, $.task_content, $._eol),
    pending_symbol: $ => '☐',
    done_symbol: $ => '✔',
    cancelled_symbol: $ => '✘',
    task_content: $ => repeat1(choice($.tag, $.text)),
    tag: $ => seq('@', $.tag_name, optional($.tag_value_group)),
    tag_name: $ => /[a-zA-Z][a-zA-Z0-9_-]*/,
    tag_value_group: $ => seq('(', $.tag_value, ')'),
    tag_value: $ => /[^)\n\r]+/,
    tags: $ => repeat1($.tag),
    text: $ => /[^\n\r@]+/,
    comment: $ => seq(optional($._indent), $.comment_text, $._eol),
    comment_text: $ => /[^☐✔✘\n\r][^\n\r]*/,
    _indent: $ => /[ \t]+/,
    _eol: $ => /\n/,
    empty_line: $ => /\n/,
  }
});
